services:
  db:
    image: mariadb:10.11
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kensyuu-2025
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 12345678
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./sql/:/sql
      # -  ./script:/docker-entrypoint-initdb.d
volumes:
  mariadb-data:


