AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ExpressApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs18.x
      CodeUri: ./
      MemorySize: 128
      Timeout: 10
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ProxyApiAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
