name: backend build and deploy warkflow
run-name: ${{ github.actor }} test

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Checkout repository
        uses: actions/setup-python@v3

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: AWS SAM build
        run: sam build --use-container

      - name: AWS SAM deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
