name: frontend build and deploy warkflow
run-name: ${{ github.actor }} test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: cd frontend | npm install
        working-directory: frontend

      - name: Pull Amplify environment
        run: amplify pull --yes --envName test

      - name: Install amplify-cli
        run: npm install -g @aws-amplify/cli
        working-directory: frontend

      - name: build
        run: npm run build
        working-directory: frontend

      - name: deploy
        run: amplify publish --yes
        working-directory: frontend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FRONTEND_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FRONTEND_AWS_SECRET_ACCESS_KEY }}
