name: Build and deploy frontend  (Stage)
run-name: Deploying frontend to stage by @${{ github.actor }}

env:
  AWS_REGION: ap-northeast-1
  AMPLIFY_ENV: stage
  AMPLIFY_APP_ID: dz8w2b63qvta8
  ROLE: arn:aws:iam::021891571401:role/elearning-amplify-stage-Role
  FRONTEND_DIR: frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        run: npm install
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Build frontend application
        run: npm run build
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Amplify Pull
        run: |
          npm install -g @aws-amplify/cli
          cd ${{ env.FRONTEND_DIR }}
          amplify pull --yes --envName ${{ env.AMPLIFY_ENV }}  --appId ${{ env.AMPLIFY_APP_ID }}
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Publish to amplify hosting
        run: amplify publish --yes
        working-directory: ${{ env.FRONTEND_DIR }}
