name: frontend build and deploy warkflow
run-name: ${{ github.actor }} test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: build
        run: npm run build
        working-directory: frontend

      - name: Amplify Pull
        run: |
          npm install -g @aws-amplify/cli
          cd frontend
          amplify pull --yes --envName test  --appId d3bmjclj64fc20

      - name: Publish to Amplify Hosting
        run: amplify publish --yes
        working-directory: frontend
